*Data Provided by Professor Soyer;
data irc;
infile 'C:\Users\ianku\Desktop\Time Seriese Practice\Financial Modeling and Econometrics\Regression Model\irc.txt';
input irc price yd rcp raaa;
time=_n_;
del=rcp-raaa;
*only focus on the first 95 period;
if time>96 then irc=.;
*regression model, irc is the dependent variable and yd, price and del are independent variables;
proc reg data=irc;
model irc=yd price del/cli;
output out=ircout p=ircpred r=error;
proc gplot data=ircout;
plot irc*ircpred;
*check residules;
proc univariate data=ircout normal;
var error;
probplot;
proc arima data=ircout;
identify var=error;
*Using proc model for White's Test;
proc model;
irc=a+b1*yd+b2*price+b3*del;
fit irc/white;
*botain VIF'S;
proc reg data=irc;
model irc=yd price del/vif;
run;
